# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts && npm install @types/node --save-dev --ignore-scripts

# Copy the entire source
COPY . .

# Build the project
RUN npm run build

CMD [ "node", "dist/index.js" ]
